// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CompressImages(arg1:main.CompressRequest):Promise<main.CompressResult>;

export function GetSupportedFormats():Promise<Array<string>>;

export function SelectFolder():Promise<string>;

export function TestFunction():Promise<string>;
