// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CompressImages(arg1) {
  return window['go']['main']['App']['CompressImages'](arg1);
}

export function GetSupportedFormats() {
  return window['go']['main']['App']['GetSupportedFormats']();
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function TestFunction() {
  return window['go']['main']['App']['TestFunction']();
}
